version: '3'
services:
  # バックエンド(docker FastAPI)
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    volumes:
      - ./back/app:/app/
    tty: true
    restart: on-failure
    working_dir: /app